// All player-visible text. Switching language = swapping this data.
export const STR = {
  title: "GUN GAME ARENA",
  subtitle: "Race up the weapon ladder. 3 kills per gun. First through the sniper wins.",
  chooseMap: "CHOOSE ARENA",
  start: "DEPLOY",
  resume: "RESUME",
  paused: "PAUSED",
  clickToPlay: "Click to take aim",
  maps: {
    dust: { name: "DUST YARD", desc: "Sun-bleached desert depot" },
    neon: { name: "NEON DISTRICT", desc: "Cold asphalt under cyan light" },
    frost: { name: "FROST DEPOT", desc: "Packed snow between containers" },
  },
  weapons: {
    pistol: "PISTOL",
    smg: "SMG",
    shotgun: "SHOTGUN",
    rifle: "RIFLE",
    sniper: "SNIPER",
  },
  hud: {
    reload: "RELOAD — R",
    reloading: "RELOADING…",
    finalGun: "FINAL GUN!",
    youLead: "You lead",
    leader: "Leader: {name}",
    respawnIn: "Respawn in {s}",
    killedBy: "Taken down by {name}",
    youKilled: "YOU TOOK DOWN {name}",
  },
  feed: { killed: "{a} ➤ {b}", advanced: "{a} advanced to {gun}" },
  end: {
    win: "VICTORY",
    lose: "DEFEAT",
    winDesc: "You cleared the whole ladder.",
    loseDesc: "{name} cleared the ladder first.",
    timeWin: "TIME! You led the ladder.",
    timeLose: "TIME! {name} led the ladder.",
    again: "PLAY AGAIN",
    menu: "CHANGE ARENA",
  },
  bots: ["Vex", "Rook", "Slag", "Piper", "Duke", "Mara"],
  you: "You",
  touch: { fire: "FIRE", jump: "JUMP", reloadBtn: "R" },
  help: {
    desktop: "WASD move · Mouse aim · Click fire · R reload · Space jump · Shift hold zoom (sniper)",
    touch: "Left: move · Right: aim · Buttons: fire / jump / reload",
  },
};
