// All player-visible text. Switching language = swapping this data.
export const STR = {
  title: "GUN GAME ARENA",
  subtitle: "Online: 5v5 Search & Destroy (plant the spike). Solo: buy-menu deathmatch vs bots.",
  start: "SOLO VS BOTS",
  resume: "RESUME",
  paused: "PAUSED",
  clickToPlay: "Click to take aim",
  maps: {
    dust: { name: "DUST YARD", desc: "Sun-bleached desert depot" },
    neon: { name: "NEON DISTRICT", desc: "Cold asphalt under cyan light" },
    frost: { name: "FROST DEPOT", desc: "Packed snow between containers" },
    haven: { name: "HAVEN", desc: "Three bomb sites — A, B, C — and a wide mid" },
  },
  weapons: {
    classic: "CLASSIC", shorty: "SHORTY", frenzy: "FRENZY", ghost: "GHOST", sheriff: "SHERIFF",
    stinger: "STINGER", spectre: "SPECTRE",
    bucky: "BUCKY", judge: "JUDGE",
    bulldog: "BULLDOG", guardian: "GUARDIAN", phantom: "PHANTOM", vandal: "VANDAL",
    marshal: "MARSHAL", outlaw: "OUTLAW", operator: "OPERATOR",
    ares: "ARES", odin: "ODIN",
    knife: "KNIFE",
  },
  shopCats: {
    sidearm: "SIDEARMS", smg: "SMGs", shotgun: "SHOTGUNS", rifle: "RIFLES",
    sniper: "SNIPERS", lmg: "MACHINE GUNS", melee: "MELEE",
  },
  shop: { title: "BUY MENU", close: "CLOSE (B)", free: "FREE",
    hint: "Buy with credits · earn 200 per kill · your weapon carries across respawns" },
  agentSelect: { title: "CHOOSE YOUR AGENT", lock: "LOCK IN" },
  agents: {
    jett:    { name: "JETT",    role: "DUELIST",   skill: "Dash",     desc: "Blink forward instantly" },
    sage:    { name: "SAGE",    role: "SENTINEL",  skill: "Mend",     desc: "Heal yourself over time" },
    reyna:   { name: "REYNA",   role: "DUELIST",   skill: "Dismiss",  desc: "Brief invuln + speed burst" },
    raze:    { name: "RAZE",    role: "INITIATOR", skill: "Boom Bot",  desc: "Lob a grenade that blasts foes" },
    phoenix: { name: "PHOENIX", role: "DUELIST",   skill: "Curveball", desc: "Flash — blinds enemies who see it" },
    omen:    { name: "OMEN",    role: "CONTROLLER",skill: "Smoke",     desc: "Drop a cloud that hides you" },
  },
  hud: {
    reload: "RELOAD — R",
    reloading: "RELOADING…",
    youLead: "You lead",
    leader: "Leader: {name}",
    respawnIn: "Respawn in {s}",
    killedBy: "Taken down by {name}",
    youKilled: "YOU TOOK DOWN {name}",
    firstTo: "FIRST TO {n}",
    abReady: "READY",
    mapLabel: "MAP",
    tapContinue: "tap to continue",
  },
  feed: { killed: "{a} ➤ {b}" },
  end: {
    win: "VICTORY",
    lose: "DEFEAT",
    winDesc: "You hit the kill target first.",
    loseDesc: "{name} hit the kill target first.",
    timeWin: "TIME! You topped the scoreboard.",
    timeLose: "TIME! {name} topped the scoreboard.",
    again: "PLAY AGAIN",
    menu: "MENU",
  },
  sd: {
    round: "ROUND", attack: "ATTACK", defend: "DEFEND",
    buyPhase: "Buy phase — press B to buy",
    carrySpike: "You carry the SPIKE — take it to a site (A / B / C)",
    holdPlant: "Hold F to PLANT the spike",
    grabSpike: "Walk over the dropped spike to grab it",
    holdDefuse: "Hold F to DEFUSE",
    spikeUp: "Spike is down — stop the defuse!",
    defuseIt: "Defuse the spike before it blows!",
    planted: "SPIKE PLANTED — {s}",
    defused: "SPIKE DEFUSED",
    detonated: "SPIKE DETONATED",
    youDied: "You died — spectate until next round",
    spectating: "Spectating — next round soon",
    roundWin: "ROUND WON",
    roundLoss: "ROUND LOST",
    reasons: { elim: "elimination", time: "time out", defuse: "spike defused", detonate: "spike detonated" },
    draw: "DRAW",
    finalScore: "Final score  {a} — {b}",
    modeNote: "Online = Search & Destroy · plant the spike at A/B/C · first to 13",
  },
  online: {
    play: "ONLINE",
    friends: "PLAY WITH FRIENDS",
    join: "JOIN THIS ROOM",
    name: "CALLSIGN",
    randomMap: "Every match drops into a random arena — you don't pick",
    connecting: "Connecting to the arena…",
    reconnecting: "Connection lost — reconnecting…",
    waitShare: "Waiting for fighters — share this link:",
    copy: "COPY",
    copied: "COPIED!",
    full: "That room is full — remove ?room= from the link to open a new one.",
    next: "Next match starting…",
    joined: "{name} joined the arena",
    left: "{name} left",
    clickAim: "Click to aim",
  },
  bots: ["Vex", "Rook", "Slag", "Piper", "Duke", "Mara"],
  you: "You",
  touch: { fire: "FIRE", jump: "JUMP", reloadBtn: "R", ability: "SKILL", shop: "BUY", aim: "ADS", use: "USE",
    rotate: "Rotate your device", rotateSub: "Play in landscape for the full HUD" },
  help: {
    desktop: "WASD move · Mouse aim · Click fire · R reload · Q ability · B buy · F plant/defuse · RMB scope",
    touch: "Left stick: move · Right side: aim · Tap FIRE / ADS / JUMP / R / SKILL / USE · 🛒 buy",
  },
};
